#!/usr/bin/env python3

from __future__ import annotations
import subprocess
import hashlib
from pathlib import Path
import logging
from rich.logging import RichHandler


FORMAT = "%(message)s"
logging.basicConfig(
    level="INFO",
    format=FORMAT,
    datefmt="[%X]",
    handlers=[RichHandler()],
)

log = logging.getLogger()

import typer

import htozupsilon as hzu
from configurations import config

app = typer.Typer(
    no_args_is_help=True,
    pretty_exceptions_show_locals=False,
)


def cache_file(file: str) -> None:
    hashed = f"data/{hashlib.md5(file.encode()).hexdigest()}.root"

    if not Path(hashed).is_file():
        log.info(f"Downloading file: {file}")
        proc = subprocess.run(
            f"xrdcp {file} {hashed}",
            shell=True,
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"Could not download input file. {proc.stdout}, {proc.stderr}"
            )
    else:
        log.info(f"File already cached: {file}")

    return hashed


@app.command()
def run():
    # print(config)
    # input_file= f"root://cmsxrootd.fnal.gov//{hzu.das.get_files('/DoubleMuon/Run2018D-UL2018_MiniAODv2_NanoAODv9_GT36-v1/NANOAOD')[0]}"
    hzu.run(
        cache_file(
            f"root://cmsxrootd.fnal.gov//{hzu.das.get_files('/DoubleMuon/Run2018D-UL2018_MiniAODv2_NanoAODv9_GT36-v1/NANOAOD')[0]}"
        )
    )


@app.command()
def add():
    hzu.add(2, 3)


@app.command()
def foo():
    hzu.foo()


if __name__ == "__main__":
    app()
