#!/usr/bin/env python3

from __future__ import annotations

import typer

import htozupsilon as hzu

app = typer.Typer(
    no_args_is_help=True,
    pretty_exceptions_show_locals=False,
)


@app.command()
def add():
    hzu.add(2, 3)


@app.command()
def foo():
    hzu.foo()


if __name__ == "__main__":
    app()
